
package sk.fillo.ws.consumer.def;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TimeService", targetNamespace = "http://provider.ws.fillo.sk/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TimeService {


    /**
     * 
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "providerTimeMillis", targetNamespace = "http://provider.ws.fillo.sk/", className = "sk.fillo.ws.consumer.def.ProviderTimeMillis")
    @ResponseWrapper(localName = "providerTimeMillisResponse", targetNamespace = "http://provider.ws.fillo.sk/", className = "sk.fillo.ws.consumer.def.ProviderTimeMillisResponse")
    @Action(input = "http://provider.ws.fillo.sk/TimeService/providerTimeMillisRequest", output = "http://provider.ws.fillo.sk/TimeService/providerTimeMillisResponse")
    public long providerTimeMillis();

}
