
package sk.fillo.ws.consumer.def;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TimeServiceService", targetNamespace = "http://provider.ws.fillo.sk/", wsdlLocation = "http://localhost/wsdl/TimeServiceService.wsdl")
public class TimeServiceService
    extends Service
{

    private final static URL TIMESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException TIMESERVICESERVICE_EXCEPTION;
    private final static QName TIMESERVICESERVICE_QNAME = new QName("http://provider.ws.fillo.sk/", "TimeServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/wsdl/TimeServiceService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TIMESERVICESERVICE_WSDL_LOCATION = url;
        TIMESERVICESERVICE_EXCEPTION = e;
    }

    public TimeServiceService() {
        super(__getWsdlLocation(), TIMESERVICESERVICE_QNAME);
    }

    public TimeServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TIMESERVICESERVICE_QNAME, features);
    }

    public TimeServiceService(URL wsdlLocation) {
        super(wsdlLocation, TIMESERVICESERVICE_QNAME);
    }

    public TimeServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TIMESERVICESERVICE_QNAME, features);
    }

    public TimeServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TimeServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TimeService
     */
    @WebEndpoint(name = "TimeServicePort")
    public TimeService getTimeServicePort() {
        return super.getPort(new QName("http://provider.ws.fillo.sk/", "TimeServicePort"), TimeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TimeService
     */
    @WebEndpoint(name = "TimeServicePort")
    public TimeService getTimeServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://provider.ws.fillo.sk/", "TimeServicePort"), TimeService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TIMESERVICESERVICE_EXCEPTION!= null) {
            throw TIMESERVICESERVICE_EXCEPTION;
        }
        return TIMESERVICESERVICE_WSDL_LOCATION;
    }

}
